StudentManagementApi
ankitmathur3193/demo-service pull request #1
Opened 2019-03-02 11:41 UTC by mudit1102

2019-03-02 11:55 UTC, ankitmathur3193 requested changes

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/entity/Address.java
> +
add country also

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/entity/DateOfBirth.java
> +
remove comparable...why do u need it?

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/entity/DateOfBirth.java
> +			{
Remove this function

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/entity/StudentEntity.java
> +	private String fatherName;
change variable to class only

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +		return students
remove TODO

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +
Same here

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/service/StudentService.java
> +				+ studentEntity.getLastName() + "#"
Make a static constant for "#" in DataConstants

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/service/StudentService.java
> +							+ id);
Log error also.

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/service/StudentService.java
> +		}
Same here,log error

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/web/rest/controller/StudentController.java
> +		return new ResponseEntity<>(StudentAssembler.convert(studentService
Add apiOperaation and apiParam

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/web/rest/controller/StudentController.java
> +				.map(StudentAssembler::convert).collect(Collectors.toList()),
same here

2019-03-02 11:55 UTC, ankitmathur3193 commented on src/main/java/com/demo/web/rest/resource/StudentResource.java
> +@Data
Remove this class.

2019-03-05 06:28 UTC, ankitmathur3193 requested changes

2019-03-05 06:28 UTC, ankitmathur3193 commented on src/main/java/com/demo/service/StudentService.java
> +		if (studentEntity == null) {
Instead of directly returning studentEntity here..return Optional wrapping studentEntity and use Optional.isPresent() instead of null check.

2019-03-05 06:28 UTC, ankitmathur3193 commented on src/main/java/com/demo/service/StudentService.java
> +			ExceptionUtils.throwBadRequestException("firstname is not valid");
Use Stringutils.isEmpty() here.

2019-03-05 06:28 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +	}
change it to return Optioinal.nullable((StudentEntity) students.get(enrollemntId))

2019-03-05 06:28 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +						&& st.getValue().getLastName().equalsIgnoreCase(lastName))
change variable name from st to student.

2019-03-05 06:28 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +	}
change variable name x to something meaningful like studentEntry or something else.

2019-03-05 06:28 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +
remove    ToDO

2019-03-05 06:28 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +
change variable names here also.

2019-03-05 06:28 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentNameIdMapRepository.java
> +	}
return Optional.nullable from here also.

2019-03-05 06:28 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentNameIdMapRepository.java
> +		nameIdMap.put(nameIdString, enrollmentId);
remove line from here.

2019-03-05 06:28 UTC, ankitmathur3193 commented on src/main/java/com/demo/service/StudentService.java
> +			ExceptionUtils
change null check to Optional.isPresent()

2019-03-05 06:33 UTC, ankitmathur3193 requested changes

2019-03-05 06:33 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentNameIdMapRepository.java
> +
see my latest commit add postConstruct and PreDestroy here to add default student details.

2019-03-05 06:35 UTC, ankitmathur3193 requested changes

2019-03-05 06:35 UTC, ankitmathur3193 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +		StudentEntity studentEntity = DataConstants.OBJECTMAPPER.readValue(student, StudentEntity.class);
rename class entity to class here also.

2019-03-05 06:37 UTC, ankitmathur3193 requested changes

2019-03-05 06:37 UTC, ankitmathur3193 commented on src/main/java/com/demo/entity/StudentEntity.java
> +	private ClassEntity classEntity;
rename classEntity to class.

2019-03-07 17:21 UTC, mudit1102 commented on src/main/java/com/demo/entity/DateOfBirth.java
> +
Removed

2019-03-07 17:21 UTC, mudit1102 commented on src/main/java/com/demo/entity/DateOfBirth.java
> +			{
Done

2019-03-07 17:33 UTC, mudit1102 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +		return students
I am no able to see this comment

2019-03-07 17:34 UTC, mudit1102 commented on src/main/java/com/demo/service/StudentService.java
> +							+ id);
Done

2019-03-07 17:35 UTC, mudit1102 commented on src/main/java/com/demo/service/StudentService.java
> +		}
Done

2019-03-09 06:07 UTC, mudit1102 commented on src/main/java/com/demo/web/rest/controller/StudentController.java
> +				.map(StudentAssembler::convert).collect(Collectors.toList()),
done

2019-03-09 06:07 UTC, mudit1102 commented on src/main/java/com/demo/web/rest/controller/StudentController.java
> +		return new ResponseEntity<>(StudentAssembler.convert(studentService
Done

2019-03-09 06:08 UTC, mudit1102 commented on src/main/java/com/demo/web/rest/resource/StudentResource.java
> +@Data
I am not able to see this import statement

2019-03-09 06:22 UTC, mudit1102 commented on src/main/java/com/demo/service/StudentService.java
> +		if (studentEntity == null) {
Done

2019-03-09 06:34 UTC, mudit1102 commented on src/main/java/com/demo/service/StudentService.java
> +			ExceptionUtils.throwBadRequestException("firstname is not valid");
done

2019-03-09 06:49 UTC, mudit1102 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +	}
done

2019-03-09 06:50 UTC, mudit1102 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +						&& st.getValue().getLastName().equalsIgnoreCase(lastName))
done

2019-03-09 06:52 UTC, mudit1102 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +	}
done

2019-03-09 06:55 UTC, mudit1102 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +
done

2019-03-09 06:58 UTC, mudit1102 commented on src/main/java/com/demo/repositroy/impl/StudentNameIdMapRepository.java
> +	}
done

2019-03-09 06:58 UTC, mudit1102 commented on src/main/java/com/demo/repositroy/impl/StudentNameIdMapRepository.java
> +		nameIdMap.put(nameIdString, enrollmentId);
done

2019-03-09 07:03 UTC, mudit1102 commented on src/main/java/com/demo/service/StudentService.java
> +			ExceptionUtils
done

2019-03-09 08:14 UTC, mudit1102 commented on src/main/java/com/demo/repositroy/impl/StudentNameIdMapRepository.java
> +
done

2019-03-09 08:16 UTC, mudit1102 commented on src/main/java/com/demo/repositroy/impl/StudentInMemoryRepositpry.java
> +		StudentEntity studentEntity = DataConstants.OBJECTMAPPER.readValue(student, StudentEntity.class);
didn't get exactly what you are trying to say here?

2019-03-09 08:20 UTC, mudit1102 commented on src/main/java/com/demo/entity/Address.java
> +
Added

2019-03-09 08:22 UTC, mudit1102 commented on src/main/java/com/demo/entity/StudentEntity.java
> +	private ClassEntity classEntity;
i had tried to rename it to class but its showing that you cant you use this identifier!!

2019-03-09 08:23 UTC, mudit1102 commented on src/main/java/com/demo/entity/StudentEntity.java
> +	private String fatherName;
Tried renaming it but shows that is reserved...

2019-03-17 07:36 UTC, ankitmathur3193 approved these changes

2019-03-17 07:37 UTC, merged